package my:service;

interface adder {
    add:    func(a: s32, b: s32) -> s32;
}
interface printer1 {
    print1: func(msg: string);
}
interface printer-n {
    print-n: func(msg: string, n: u32);
}

world service {
    import adder;
    import printer1;
    import printer-n;

    include wasi:http/service@0.3.0-rc-2026-01-06;
}
