package example:fan-in;

world service {
    import my:service/adder;
    import my:service/adder-async;
    import my:service/messenger;
    import my:service/messenger-async;
    import my:service/printer1;
    import my:service/printer1-async;
    import my:service/printer-n;
    import my:service/shapes;
    import my:service/shapes-handles;
    import my:service/async-bucket-types;
    import my:service/async-bucket;

    include wasi:http/service@0.3.0-rc-2026-01-06;
}
