package my:service;

interface type-erased-middleware {
    before-call: func(name: string);
    should-block-call: func(name: string) -> bool;  // true = block downstream
    after-call: func(name: string);
}

world printer-mdl {
    export type-erased-middleware;
}
