[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "runner"
path = "src/main.rs"

[dependencies]
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
env_logger = { workspace = true }
flate2 = { workspace = true }
