[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "runner"
path = "src/main.rs"

[dependencies]
wasmtime = { version = "41.0.1", features = ["cranelift", "incremental-cache"] }
#wasmtime = { path = "../../../research/wasm/wasmtime/crates/wasmtime", features = ["cranelift", "incremental-cache"] }
#wasmtime-wasi = { path = "../../../research/wasm/wasmtime/crates/wasi", features = ["p3"] }
wasmtime-wasi = { version = "41.0.1", features = ["p3"] }
#wasi-common = { path = "../../../research/wasm/wasmtime/crates/wasi-common" }
wasmtime-wasi-http = { version = "41.0.1", features = ["p3"] }
#wasmtime-wasi-http = { path = "../../../research/wasm/wasmtime/crates/wasi-http", features = ["p3"] }
wasm-compose = "0.244.0"
anyhow = "1.0.86"
tokio = { version = "1.48.0", features = ["net", "rt-multi-thread", "time", "rt", "macros", "fs"] }
tokio-util = "0.7.16"
http = "1.3.1"
http-body = "1.0.1"
http-body-util = "0.1.3"
bytes = { version = "1.10.1", default-features = false }
futures = { version = "0.3.31", default-features = false, features = ['alloc', 'async-await'] }
tempfile = "3.23.0"
env_logger = "0.11.5"
flate2 = "1.1.4"
hyper = "1.8.1"
