name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:

  # Run CLI across OS targets
  build_and_test:
    name: Build + Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@1.93.0
      - run: cargo --version

      - name: Install wasm-tools
        run: cargo install wasm-tools@1.244.0
      - name: Install wkg
        run: cargo install wkg@0.13.0
      - name: Install splicer
        run: cargo install splicer@2.0.0-rc2
      - name: Install cviz
        run: cargo install cviz@2.0.0-rc2
      - name: Install wac
        run: cargo install wac-cli@0.9.0
      - name: Add wasi target
        run: rustup target add wasm32-wasip1

      - name: Build + Test
        run: ./run.sh __testme
